apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredLabels
metadata:
  name: rolebinding-access-control-constraint
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["RoleBinding"]
  parameters:
    labels:
      - admin