apiVersion: v1
kind: Secret    # yaml da https://kubernetes.io/docs/concepts/configuration/secret/
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-user: bW9uZ291c2Vy
  mongo-password: bW9uZ29wYXNzd29yZA==


