apiVersion: templates.gatekeeper.sh/v1.0
kind: ConstraintTemplate
metadata:
  name: k8s-lables-are-required
  annotations:
    metadata.gatekeeper.sh/title: "Lables are required"
    metadata.gatekeeper.sh/version: 1.0.0
    description: >-
        Si richiede che tutte le risorse contengano label con valori
spec:
  crd:
    spec:
      names:
        kind: k8s-lables-are-required
      validation:
        openAPIV3Schema:
          type: object
          properties:
            message:
              type: string
            labels:
              type: array
              description: >-
                Un elenco di labels e valori che devono essere specificate.
              items:
                type: object
                properties:
                  key:
                    type: string
                    description: >-
                     label richiesta.
                  allowedRegex:
                    type: string
                    description: >-
                      Se specificato, un'espressione regolare il valore dell'annotazione
                      deve combaciare. Il valore deve contenere almeno una corrispondenza per
                      l'espressione regolare
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8srequiredlabels
        get_message(parameters, _default) = msg {
          not parameters.message
          msg := _default
        }
        get_message(parameters, _default) = msg {
          msg := parameters.message
        }
        violation[{"msg": msg, "details": {"missing_labels": missing}}] {
          provided := {label | input.review.object.metadata.labels[label]}
          required := {label | label := input.parameters.labels[_].key}
          missing := required - provided
          count(missing) > 0
          def_msg := sprintf("you must provide labels: %v", [missing])
          msg := get_message(input.parameters, def_msg)
        }
        violation[{"msg": msg}] {
          value := input.review.object.metadata.labels[key]
          expected := input.parameters.labels[_]
          expected.key == key
          # do not match if allowedRegex is not defined, or is an empty string
          expected.allowedRegex != ""
          not re_match(expected.allowedRegex, value)
          def_msg := sprintf("Label <%v: %v> does not satisfy allowed regex: %v", [key, value, expected.allowedRegex])
          msg := get_message(input.parameters, def_msg)