apiVersion: constraints.gatekeeper.sh/v1beta1
kind: ClusterRequiredLabels
metadata:
  name: must-have-labels
  spec:
match:
    kinds:
    - apiGroups: [""]
      kinds: ["Pod"]
    parameters:
      labels: ["app", "env"]